### ISSUE TITLE
Issue with Nearest Neighbour spatial filter

### ISSUE THREAD

**Issue by rfj82982** [MxUI/MUI#33] opened 2019-06-13 16:14 UTC
I have an issue with the nearest neighbour spatial filters. The filter does not pick up properly points on a boundary even if the two meshes are conformal. 
In the following example i have a square with a 9x9 mesh. In the left and bottom boundaries points are not selected correctly. 
![ResuPoint_SameMesh](https://user-images.githubusercontent.com/35581400/59448456-116b5580-8dfd-11e9-8d26-6836a01dd81e.png)
A simple way to resolve the problem was to change the support geometry for the from point 
    
    inline geometry::any_shape<CONFIG> support( point_type focus ) const {
		return geometry::point<CONFIG>( focus );
    }

to sphere 

    inline geometry::any_shape<CONFIG> support( point_type focus ) const {
                return geometry::sphere<CONFIG>( focus, 1.e-2 );
    }

This is now the result
![ResuSphere_SameMesh](https://user-images.githubusercontent.com/35581400/59448823-dddcfb00-8dfd-11e9-969e-ccffb84180da.png)

Note that the tolerance that i have used for the sphere is the same that i passed to the original  NN filter based on point.
I have a code to test the problem where a scalar field is passed between two solvers. i develop the example as an extra example for the MUI-demo.

**Comment by SLongshaw** [comment] 2019-06-21 11:39
Thank you for the very detailed bug report, this is indeed unintended behaviour for the NN filter that happens due to the underlying cell based search structure (this isn't a problem if all points to be considered for neighbours are within the cell that the support point lies in but in your case, this doesn't happen as your support is the same size as your cells, so whether points of interest are in a (MUI) cell will depend on luck due to rounding.

Your proposed solution is a reasonable one but we will need to think about how to make it non case-specific, this probably needs an iterative approach to try and minimise overhead (technically a nn search might need to consider a full brute-force approach but clearly this is not viable in most scenarios) while allowing for scenarios like yours where the nearest neighbour technically falls into a cell surrounding the one that contains the focus point.

I'd be interested to hear other MUI developers thoughts on the best way forward?

**Comment by SLongshaw** [comment] 2019-07-08 13:42
Following a closer examination of the problem and solution, this functionality is actually already implemented in the form of the "pseudo" nearest neighbour spatial sampler, therefore I am closing this bug as there is no need for the "fix" to be applied to the normal nn sampler (which actually works as expected).

**Closed by SLongshaw** 2019-07-08 13:42 UTC
